InternLM/xtuner

- xtuner/model/sft.py
In old version, activation_checkpointing is not applied to LoRA fine-tuning.
> [Fix] Fix activation checkpointing bug

- requirements/runtime.txt
Main reasons:
1. ChatGLM3 tokenizer `save_pretrained` error: https://github.com/InternLM/xtuner/issues/199#issuecomment-1791853794
2. The expected signatures of `gradient_checkpointing_enable` have been changed: https://github.com/huggingface/transformers/pull/27020, https://github.com/huggingface/transformers/pull/27073
> [Fix] Temporarily limit the version of `transformers`

- requirements.txt
- requirements/modelscope.txt
- requirements/runtime.txt
- setup.py
- xtuner/configs/mixtral/mixtral_8x7b_full_oasst1_internlm_template_e3.py
- xtuner/configs/mixtral/mixtral_8x7b_qlora_oasst1_internlm_template_e3.py
Due to the lack of official dialogue templates from Mixtral, we use InternLM's dialogue templates for its SFT fine-tuning.
```bash
xtuner train mixtral_8x7b_qlora_oasst1_internlm_template_e3 --deepspeed deepspeed_zero2
#Full Parameters（with slurm）
srun ${SRUN_ARGS} xtuner train mixtral_8x7b_full_oasst1_internlm_template_e3 --deepspeed deepspeed_zero3 --launcher slurm
> [Feature] Support Mixtral 8x7b

- xtuner/dataset/map_fns/dataset_map_fns/alpaca_map_fn.py
To enhance the versatility of `alpaca_map_fn`
> [Fix] Remove `system` for `alpaca_map_fn`

- xtuner/dataset/utils.py
Ignore output's loss by `output_with_loss=False` (default to `True`)
e.g.,
```diff
def alpaca_map_fn(example):
if example.get('output') == '<nooutput>':
return {'conversation': []}
else:
return {
'conversation': [{
'input': f"{example['instruction']}\n{example['input']}",
'output': example['output'],
+               'output_with_loss': False
}]
}
```
> [Improve] Add `output_with_loss` for dataset process

- xtuner/model/modules/dispatch/__init__.py
- xtuner/model/modules/dispatch/llama.py
- xtuner/model/modules/dispatch/triton_kernels/rms_norm.py
1. Fix dispatch to support transformers >= 4.36
2. Add `USE_TRITON_KERNEL` environment variable. Triton Kernels will not be used by default. One can set `USE_TRITON_KERNEL` to 1 to use Triton Kernels, such as `USE_TRITON_KERNEL=1 xtuner train ...`.
> [Fix] Fix dispatch to support transformers>=4.36 & Add USE_TRITON_KERNEL environment variable

- xtuner/dataset/map_fns/dataset_map_fns/msagent_map_fn.py
使用修改后得到的数据如下所示：
```json
{
"conversation": [
{
"system": "你是一个可以调用外部工具的助手，可以使用的工具包括：\n{'modelscope_text-address': \"针对中文的地址信息，识别出里面的元素，包括省、市、区、镇、社区、道路、路号、POI、楼栋号、户室号等\\n输入参数: {'text': '用户输入的地址信息'}\"}\n如果使用工具请遵循以下格式回复：\n```\nThought:思考你当前步骤需要解决什么问题，是否需要使用工具\nAction:工具名称，你的工具必须从 [['modelscope_text-address']] 选择\nAction Input:工具输入参数\n```\n工具返回按照以下格式回复：\n```\nResponse:调用工具后的结果\n```\n如果你已经知道了答案，或者你不需要工具，请遵循以下格式回复\n```\nThought:给出最终答案的思考过程\nFinal Answer:最终答案\n```\n开始!\n",
"input": "现在我给你另一条地址，请识别出里面的元素。输入地址：北京市海淀区中关村大街27号\n",
"output": "Action:modelscope_text-address\nAction Input:{'text': '北京市海淀区中关村大街27号'}\n\n\n\n"
},
{
"system": "Response:{'prov': '北京市', 'city': '北京市', 'district': '海淀区', 'road': '中关村大街', 'number': '27号'}\n",
"output": "Final Answer:地址识别json表示：{\"prov\": \"北京市\", \"city\": …
```
> [Fix] Fix extract_json_objects

- xtuner/dataset/samplers/length_grouped.py
E.g.,
```
n_data = 10003
world_size = 8
per_device_batch_size = 16
round_up = True
```
```
num_samplers = ceil(10003 / 8) = 1251
total_size = 1251 * 8 = 10008
iteration = ceil(10008 / 16 / 8) = 79
Iter 0-77, bs = 8 * 16 = 128
Iter 78, bs = 10008 - 128 * 78 = 24
```
This inconsistent BatchSize (128 v.s. 24) leads to an error when using DeepSpeed,
```
Invalidate trace cache @ step 305: expected module 4, but got module 2
```
After fix
```
num_samplers = ceil(10003 / 8 / 16) * 16 = 1264
total_size = 1264 * 8 = 10112
iteration = ceil(10112 / 16 / 8) = 79
Iter 0-77, bs = 8 * 16 = 128
Iter 78, bs = 10112 - 128 * 78 = 128
```
> [Fix] Inconsistent BatchSize of `LengthGroupedSampler`

- docs/zh_cn/user_guides/llava_offline.md
- xtuner/dataset/llava.py
- xtuner/tools/process_untokenized_llava_data.py
离线处理llava数据可以尝试在XTuner main分支基础上
修改：
1. xtuner/dataset/llava.py
2. xtuner/dataset/map_fns/dataset_map_fns/llava_map_fn.py
新增：
1. xtuner/configs/internlm/internlm2_chat_7b/internlm2_chat_7b_llava.py
2. xtuner/tools/process_untokenized_llava_data.py
- 首先通过xtuner/tools/process_untokenized_llava_data.py离线处理llava训练数据中的文本部分
```
python xtuner/tools/process_untokenized_llava_data.py llava_cfg.py --save-folder llava_data
```
- 处理后可以读取数据集查看是否符合预期
```
from datasets import load_from_disk
ds = load_from_disk('llava_data')
print(ds)
```
- 之后修改 llava_cfg.py 配置文件中的llava_dataset，新增 `offline_processed_text_folder = ${save-folder}` 字段就可以直接读取离线处理后的数据了
> support offline process llava data

- xtuner/dataset/llava.py
- xtuner/engine/hooks/evaluate_chat_hook.py
- xtuner/model/llava.py
- xtuner/tools/chat.py
- xtuner/tools/mmbench.py
When the input type is fp32 and the model type is bf16, CLIP automatically performs type conversion, so no error occurs. However, if we switch to other CLIP models such as SigLIP, an error will be thrown.
> Fix type error when the visual encoder is not CLIP

- requirements/runtime.txt
Registering a causal mask in `LlamaModel` (in transformers 4.38) is not friendly for very large `max_position_embeddings`. Refer to https://github.com/huggingface/transformers/blob/v4.38.0/src/transformers/models/llama/modeling_llama.py#L921-L923
> Limit transformers != 4.38

- xtuner/engine/hooks/dataset_info_hook.py
Before:
`split_list([-200, 123, 123], -200)` returns `[[-200, 123, 123]]`
After:
`split_list([-200, 123, 123], -200)` returns `[[], [123, 123]]`
> [Fix] Enhance `split_list` to support `value` at the beginning

- xtuner/engine/hooks/__init__.py
- xtuner/engine/hooks/hf_checkpoint_hook.py
```diff
custom_hooks = [
+    dict(type=HFCheckpointHook),
]
```
The HF model will be saved at `work_dir/timestamp/hf_model`
1. As the priority of `HFCheckpointHook` is 95 which is lower than `CheckpointHook` in MMEngine, the hf model is saved only after the normal checkpoint saving process is complete. So feel free to use it.
> [Feature] add HFCheckpointHook to auto save hf model after the whole training phase

- xtuner/engine/hooks/dataset_info_hook.py
During the training process, if the test loop is configured in the user settings, it will trigger the construction of the test dataset, which is unexpected.
> Remove test info in DatasetInfoHook

- xtuner/model/utils.py
- xtuner/tools/model_converters/pth_to_hf.py
- xtuner/utils/zero_to_any_dtype.py
Mixtral 8x7B ZeRO3 : 110GB
Mistral 7B ZeRO3: 15GB
> [Enhancement] Optimizing Memory Usage during ZeRO Checkpoint Convert

- xtuner/tools/train.py
When users process untokenized dataset offline, it is possible that `use_varlen_attn` is True but `pack_to_max_length` is False.
> [Bug] fix cfg check

- xtuner/engine/hooks/evaluate_chat_hook.py
在运行 4 节点 32卡的 LLaVA-InternLM2-20B 的预训练时，每次到eval阶段除master节点之外都会报错 FileNotExist，经过阅读 xtuner 和 mmengine 的代码后定位到问题：
mmengine在多节点训练时，默认只在master节点保存log/vis_data等信息，这会导致worker节点的没有 vis_data 这个文件夹，但是 xtuner 在保存eval结果的时候是每个节点都保存一份，而且在打开文件的时候没有做父文件夹是否存在的验证，因此导致了除master节点外都因为文件夹不存在而挂掉。。。
修复方式也很简单：保证只在master节点存储结果（利用mmengine提供的 `master_only` 装饰器），每次保存前利用mmengine提供的接口 `mkdir_or_exist` 进行文件夹存在性检查。
> [fix] fix save eval result failed with mutil-node pretrain

- xtuner/configs/llava/llama3_8b_instruct_clip_vit_large_p14_336/README.md
- xtuner/model/llava.py
- xtuner/model/sft.py
- xtuner/tools/model_converters/pth_to_hf.py
```
xtuner pth_to_hf $CONFIG $PTH $SAVE_PATH --save-format [xtuner, official, huggingface]
```
More details can be found on https://github.com/LZHgrla/xtuner/blob/a1a0ce8f7f47d1e1079d9bc17876980225dbb4df/xtuner/configs/llava/llama3_8b_instruct_clip_vit_large_p14_336/README.md#model-conversion
> [Improve] Support the export of various LLaVA formats with `pth_to_hf`

- xtuner/configs/dpo/internlm/internlm2_chat_1_8b_dpo_full.py
- xtuner/configs/dpo/internlm/internlm2_chat_1_8b_dpo_full_varlenattn.py
- xtuner/configs/dpo/internlm/internlm2_chat_1_8b_dpo_full_varlenattn_jsonl_dataset.py
- xtuner/configs/dpo/internlm/internlm2_chat_7b_dpo_qlora_varlenattn.py
- xtuner/configs/dpo/llama/llama3_8b_instruct_dpo_qlora_varlenattn.py
- xtuner/engine/hooks/dataset_info_hook.py
`DatasetInfoHook` gets error when dpo training.
DPO dataset get `chosen_ids` and `rejected_ids` instead of `input_ids`.
https://github.com/InternLM/xtuner/blob/8adc8d4a5d6f5a33474f85093d8bb43c24c2b32e/xtuner/engine/hooks/dataset_info_hook.py#L30
You can reproduce with any dpo training, such as [internlm2_chat_1_8b_dpo_full](https://github.com/InternLM/xtuner/blob/main/xtuner/configs/dpo/internlm/internlm2_chat_1_8b_dpo_full.py)
> [Feature] Support the DatasetInfoHook of DPO training

- xtuner/model/dpo.py
- xtuner/model/orpo.py
> [Enhance]: Fix sequence parallel memory bottleneck in DPO & ORPO

- docs/zh_cn/training/modify_settings.rst
- docs/zh_cn/training/open_source_dataset.rst
- xtuner/configs/qwen/qwen1_5/qwen1_5_4b/qwen1_5_4b_qlora_alpaca_e3_openmind.py
- xtuner/dataset/__init__.py
- xtuner/tools/train.py
- xtuner/tools/utils.py
in configuration, can add extra model_resource:
```
from openmind_hub import snapshot_download
pretrained_model_name_or_path = 'Tianjin_Ascend/Qwen1.5-4B'
model_resource = {
"fn": snapshot_download,
"args":{ 
}
}
```
> Add functionality to download models from sources other than HuggingFace

- xtuner/engine/_strategy/deepspeed.py
- xtuner/engine/hooks/varlen_attn_args_to_messagehub_hook.py
- xtuner/model/llava.py
- xtuner/model/modules/dispatch/triton_kernels/rms_norm.py
- xtuner/model/modules/dispatch/triton_kernels/rotary.py
- xtuner/model/reward.py
- xtuner/model/sft.py
- xtuner/model/transformers_models/mixtral/modeling_mixtral.py
- xtuner/parallel/sequence/comm.py
- xtuner/tools/chat.py
- xtuner/tools/eval_refcoco.py
- xtuner/tools/mmbench.py
- xtuner/tools/model_converters/merge.py
- xtuner/tools/model_converters/split.py
- xtuner/tools/utils.py
- xtuner/utils/device.py
🚀This PR enables the users of xtuner to leverage the Ascend NPU for fine-tuning .
This PR primarily addresses the initial refactoring of device-independent code, enabling users of xtuner to perform fine-tuning on NPU devices. Currently, this PR involves the following modules: single-device LoRA fine-tuning, single-device full-parameter fine-tuning, LoRA merging, and model conversation.
> Add Ascend NPU as a backend

- xtuner/_lite/patches/base.py
- xtuner/_lite/patches/llama.py
This PR introduces improvements for gradient computation and clipping in hybrid/tensor parallel environments, addressing critical issues in tensor parallelism scenarios.
**Problem**: Existing `_foreach` operators fail when parameters reside on different device meshes (common in hybrid parallelism setups like FSDP+TP).  
**Solution**: Implement mesh-aware gradient clipping by:
1. Grouping parameters by device mesh
2. Applying mesh-wise norm calculations
3. Performing global reduction
Enables proper clipping for models combining different parallel strategies (e.g., ViT with pure FSDP and LM with FSDP+TP).
---
**Issue**: `RuntimeError` when using tensor parallelism (`tp_size > 1`) without Liger kernel  
**Root Cause**: Mismatched tensor types between `DTensor` logits and regular `Tensor` …
> [Feature][Fix] Enhance gradient handling for hybrid/tensor parallelism

- xtuner/_lite/algorithms/ppo/dataset.py
- xtuner/_lite/algorithms/sft/dataset.py
- xtuner/_lite/datasets/cache.py
- xtuner/_lite/datasets/json.py
- xtuner/_lite/datasets/jsonl.py
- xtuner/_lite/datasets/utils/convert.py
- xtuner/_lite/datasets/utils/utils.py
- xtuner/_lite/parallel/setup.py
1. Make `SftTokenizeFunction` and `PPOTokenizeFunction` inherit from `CachableTokenizeFunction` to facilitate hash calculation, making cached tokenized data more accurate
2. Fix issues in `JsonlDataset` and `JsonlDataset` where `num_tokens` still has a probability of being `None` when `tokenize_fn` is passed
3. Fix minor docformatter issues in CI
> [Fix] Fix tokenization hash

- xtuner/_lite/datasets/cache.py
- xtuner/_lite/datasets/jsonl.py
1. support custom hash algorithm by setting HASH_METHOD.
2. Save memory usage when initializing the dataset cache.
> Update jsonl dataset

- ci/scripts/test_grpo_trainer.py
- xtuner/v1/ray/config/worker.py
- xtuner/v1/ray/rollout/controller.py
- xtuner/v1/ray/rollout/worker.py
Append eos_token_ids in rollout worker according to finish reason manually, and this logic will be removed when lmdeploy supports to return stop_tokens
> [bugFix] append eos_token_ids in rollout worker manually

- examples/v1/pretrain_qwen3_tiny.py
- tests/resource/pretrain_example_data.jsonl
- xtuner/v1/datasets/pt_tokenize_fn/__init__.py
- xtuner/v1/datasets/pt_tokenize_fn/text.py
This pull request introduces a new example script for pretraining a Qwen3 model using the `xtuner` v1 API, and adds supporting components for dataset tokenization. The main changes include the implementation of a configurable pretraining tokenization function, updates to the dataset module structure, and the addition of a sample dataset for testing.
**New pretraining example and dataset:**
* Added a new example script `pretrain_qwen3_tiny.py` that demonstrates how to configure and launch a pretraining run for the Qwen3 model, including model, optimizer, dataset, dataloader, and trainer configurations.
* Added a small sample dataset `pretrain_example_data.jsonl` with example text data for pretraining demonstrations and tests.
**Tokenization function and configuration:**
* Implemented …
> [Feature] Add Pretraining Example

- xtuner/v1/train/trainer.py
1. **[Fix]** originally `checkpoint_interval` was defined and implemented in trainer but was never exposed to `Trainer.from_config`, thus any attempt to set ckpt interval from cli interface would be in vain (the program always saves ckpt only by the end of training). This PR tries to fix this issue.
~~2. **[Enhance]** `sp_size` was declared in `FSDPConfig` but was defined again in trainer args. This PR removes this redundant `sp_size`.~~
> [Fix] add checkpoint options to trainer cfg

- tests/train/test_trainer.py
- xtuner/v1/engine/vision_compose_train_engine.py
- xtuner/v1/model/moe/moe.py
1. Fix bug. `BalancingLossConfig` and `ZLossConfig` should inherit from `pydantic.BaseModel `rather than `xtuner.v1.model.BaseModel`
2. Fix bug. `VisionComposeConfigProtocol.hf_config` should be `property`, otherwise it will fail the building for `TrainerConfig`
> [Fix] Fix the building and dumping of
